Repository Ogutu-Brian/questioners, pull requests merged in 2019-03, with the labels that each got.

#2 #164275518 Add GitHub integration to pivotal tracker
  README.md
Labels: Peer Review, TM Review

#3 [chore #164275534] Upgrade Django 2.1.2 to Django 2.1.7
  api/requirements.txt
Labels: Peer Review, TM Review

#1 #164275556 Added swagger documentation to the API
  .gitignore
  api/config/settings.py
  api/config/urls.py
  api/requirements.txt
Labels: Peer Review, TM Review

#5 #164297869 Configure PostgreSQL as default DB Engine
  .env-example
  README.md
  api/config/settings.py
Labels: TM Review

#4 #164275560 Integrate CI and maintainability tool
  .coveragerc
  .gitignore
  .travis.yml
  README.md
  api/config/settings.py
  api/requirements.txt
  api/users/tests.py
Labels: TM Review

#7 #164275574 Adds configurations and settings to deploy to heroku
  .env-example
  .gitignore
  .travis.yml
  Procfile
  api/config/settings.py
  requirements.txt
Labels: TM Review

#6 #164275603 Post Meetup Endpoint for Questioner (Backend)
  .codeclimate.yml
  .gitignore
  .travis.yml
  api/.coveragerc
  api/config/settings.py
  api/config/urls.py
  api/meetups/__init__.py
  api/meetups/admin.py
  api/meetups/apps.py
  api/meetups/migrations/0001_initial.py
  api/meetups/migrations/0002_auto_20190305_1839.py
  api/meetups/migrations/__init__.py
  api/meetups/models.py
  api/meetups/serializers.py
  api/meetups/tests/__init__.py
  api/meetups/tests/test_data.json
  api/meetups/tests/test_meetups.py
  api/meetups/urls.py
  api/meetups/views.py
  api/users/admin.py
  api/users/migrations/0002_auto_20190304_1941.py
  api/utils/validators.py
  requirements.txt
Labels: Peer Review, TM Review

#8 #164361710 Login Basic and Google OAuth2 Authentication
  .env-example
  api/auth/serializers.py
  api/auth/urls.py
  api/auth/views.py
  api/config/settings.py
  api/config/swagger.py
  api/config/urls.py
  api/users/admin.py
  api/users/models.py
  api/users/tests.py
  api/users/tests/__init__.py
  api/users/tests/tests_login.py
  requirements.txt
Labels: TM Review

#10 #164368442 Post User Endpoint for Questioner
  .env-example
  README.md
  api/.coveragerc
  api/auth/serializers.py
  api/auth/urls.py
  api/auth/views.py
  api/config/settings.py
  api/config/urls.py
  api/meetups/migrations/0001_initial.py
  api/meetups/migrations/0002_auto_20190305_1839.py
  api/meetups/migrations/0002_auto_20190311_1522.py
  api/users/admin.py
  api/users/migrations/0001_initial.py
  api/users/migrations/0002_auto_20190304_1941.py
  api/users/tests/test_change_password_api.py
  api/users/tests/test_signup.py
  api/users/tests/tests_login.py
  requirements.txt
Labels: TM Review

#12 #164535149 Remove google oauth2 tests
  api/config/settings.py
  api/users/admin.py
  requirements.txt
Labels: TM Review

#11 #164361854 User should be able to reset password
  .env-example
  api/auth/views.py
  api/config/settings.py
  api/config/swagger.py
  api/config/urls.py
  api/users/migrations/0001_initial.py
  api/users/tests/test_password_rest.py
  api/users/tests/tests.py
  api/users/tests/tests_login.py
  requirements.txt
Labels: TM Review

#13 #164363505 View Meetups endpoints for Questioner App (API)
  api/.coveragerc
  api/config/settings.py
  api/config/swagger.py
  api/config/urls.py
  api/meetups/models.py
  api/meetups/serializers.py
  api/meetups/tests/initial_setup.py
  api/meetups/tests/test_meetups.py
  api/meetups/urls.py
  api/meetups/views.py
  api/utils/validators.py
  requirements.txt
Labels: TM Review

#15 #164363472 Update Meetup Endpoint
  api/config/settings.py
  api/config/swagger.py
  api/meetups/serializers.py
  api/meetups/tests/test_update_meetup.py
  api/meetups/urls.py
  api/meetups/views.py
  api/utils/validators.py
Labels: TM Review

#19 #164363505 Update pagination and pagination documentation (View Meetups)
  api/config/settings.py
  api/config/swagger.py
  api/meetups/views.py
Labels: TM Review

#16 #164523189 User can respond to meetup rsvp
  api/.coveragerc
  api/auth/serializers.py
  api/auth/urls.py
  api/auth/views.py
  api/config/settings.py
  api/config/swagger.py
  api/meetups/admin.py
  api/meetups/migrations/0003_rsvp.py
  api/meetups/migrations/0004_auto_20190312_1521.py
  api/meetups/migrations/0005_auto_20190312_1747.py
  api/meetups/migrations/0006_auto_20190314_0711.py
  api/meetups/models.py
  api/meetups/serializers.py
  api/meetups/tests/test_meetups.py
  api/meetups/urls.py
  api/meetups/views.py
  api/users/tests/tests.py
  requirements.txt
Labels: TM Review

#18 #164363488 Delete A Specific Meetup by Id
  api/config/swagger.py
  api/meetups/tests/test_delete_meetups.py
  api/meetups/urls.py
  api/meetups/views.py
Labels: TM Review

#14 #164275730 Post a question to a specific meetup(Endpoint)
  api/config/settings.py
  api/config/swagger.py
  api/config/urls.py
  api/meetups/migrations/0001_initial.py
  api/meetups/migrations/0002_auto_20190311_1522.py
  api/meetups/migrations/0003_rsvp.py
  api/meetups/migrations/0004_auto_20190312_1521.py
  api/meetups/migrations/0005_auto_20190312_1747.py
  api/meetups/migrations/0006_auto_20190314_0711.py
  api/questions/__init__.py
  api/questions/admin.py
  api/questions/apps.py
  api/questions/migrations/0001_initial.py
  api/questions/migrations/__init__.py
  api/questions/models.py
  api/questions/serializers.py
  api/questions/tests/__init__.py
  api/questions/tests/basetests.py
  api/questions/tests/test_questions.py
  api/questions/urls.py
  api/questions/views.py
  requirements.txt
Labels: TM Review

#21 #164523154 User should be able to view questions posted on specific meetups
  api/config/settings.py
  api/config/swagger.py
  api/meetups/migrations/0001_initial.py
  api/meetups/serializers.py
  api/meetups/tests/test_meetups.py
  api/meetups/views.py
  api/questions/serializers.py
  api/questions/tests/basetests.py
  api/questions/tests/test_questions.py
  api/questions/urls.py
  api/questions/views.py
  api/utils/validators.py
  requirements.txt
Labels: TM Review

#22 #164701176 Update documentation
  .env-example
  api/config/settings.py
  api/config/swagger.py
  api/meetups/tests/test_meetups.py
  api/meetups/urls.py
  api/meetups/views.py
Labels: TM Review

#26 #164721952 Return User details instead of user UID when viewing resources(CRUD)
  .codeclimate.yml
  api/config/swagger.py
  api/config/urls.py
  api/meetups/serializers.py
  api/questions/serializers.py
  api/questions/urls.py
  api/questions/views.py
  api/users/serializers.py
Labels: Peer Review

#20 #164523177 User should be able to delete a question
  api/config/swagger.py
  api/questions/migrations/0002_auto_20190313_1103.py
  api/questions/migrations/0003_merge_20190320_1606.py
  api/questions/tests/basetests.py
  api/questions/tests/test_delete_questions.py
  api/questions/tests/test_questions.py
  api/questions/urls.py
  api/questions/views.py
Labels: Peer Review, TM Review

#17 #164523178 User Should be able edit question they posted
  README.md
  api/.coveragerc
  api/config/settings.py
  api/config/swagger.py
  api/config/urls.py
  api/meetups/migrations/0001_initial.py
  api/meetups/views.py
  api/questions/migrations/0001_initial.py
  api/questions/serializers.py
  api/questions/tests/basetests.py
  api/questions/tests/test_edit_question.py
  api/questions/urls.py
  api/questions/views.py
  api/utils/validators.py
  requirements.txt
Labels: WIP

#24 #164688507 Vote Questions (API)
  api/config/swagger.py
  api/meetups/tests/test_delete_meetups.py
  api/meetups/tests/test_update_meetup.py
  api/meetups/urls.py
  api/meetups/views.py
  api/questions/admin.py
  api/questions/migrations/0002_questionvote.py
  api/questions/migrations/0003_auto_20190319_0043.py
  api/questions/migrations/0004_auto_20190319_0453.py
  api/questions/migrations/0005_merge_20190320_1506.py
  api/questions/migrations/0006_merge_20190321_0928.py
  api/questions/models.py
  api/questions/serializers.py
  api/questions/tests/test_votes.py
  api/questions/urls.py
  api/questions/views.py
Labels: Peer Review

#23 #164688413 User can post answers to a question
  api/answers/serializers.py
  api/answers/tests/basetests.py
  api/answers/tests/test_answers.py
  api/answers/urls.py
  api/answers/views.py
  api/config/settings.py
  api/questions/tests/basetests.py
Labels: Peer Review, TM Review

#30 #164688417 user/admin can delete answer
  api/answers/migrations/0001_initial.py
  api/answers/migrations/0002_auto_20190318_1458.py
  api/answers/tests/test_delete_answer.py
  api/answers/urls.py
  api/answers/views.py
  api/config/swagger.py
Labels: Peer Review, TM Review

#33 #164722615 Add environment variable for swagger url
  .env-example
  api/config/swagger.py
Labels: TM Review

#29 #164688519 Vote for Answers (PATCH)
  api/answers/admin.py
  api/answers/migrations/0001_initial.py
  api/answers/migrations/0002_remove_answervote_votes.py
  api/answers/models.py
  api/answers/serializers.py
  api/answers/tests/basetests.py
  api/answers/tests/test_answers.py
  api/answers/tests/test_voting_answers.py
  api/answers/urls.py
  api/answers/views.py
  api/config/swagger.py
  api/questions/views.py
  requirements.txt
Labels: Peer Review

#36 #164822926 Fix the social auth functionality
  api/config/swagger.py
Labels: Peer Review

#35 #164869458 View specific question for a specific meetup
  api/config/swagger.py
  api/questions/tests/basetests.py
  api/questions/tests/test_questions.py
  api/questions/urls.py
  api/questions/views.py
Labels: Peer Review

#32 #164856306 Update specific field on a question
  api/config/swagger.py
  api/questions/serializers.py
  api/questions/tests/basetests.py
  api/questions/tests/test_edit_question.py
  api/questions/views.py
Labels: Peer Review

#31 #164822920 Add rsvps to meetups Responses (API)
  api/config/swagger.py
  api/meetups/models.py
  api/meetups/serializers.py
  api/meetups/tests/test_meetups.py
  api/meetups/urls.py
  api/meetups/views.py
  api/questions/models.py
Labels: Peer Review, TM Review

#34 #164870259 User can logout
  api/answers/views.py
  api/auth/urls.py
  api/auth/views.py
  api/config/swagger.py
  api/config/urls.py
  api/meetups/tests/initial_setup.py
  api/meetups/tests/test_delete_meetups.py
  api/meetups/views.py
  api/questions/views.py
  api/users/migrations/0002_tokenblacklist.py
  api/users/models.py
  api/users/tests/tests_login.py
  api/utils/token_validation.py
Labels: Peer Review, TM Review
